services:
  frontend:
    build:
      context: ./tunedown
      dockerfile: dev.Dockerfile
    environment:
      NODE_ENV: dev
    ports:
      - "3000:3000"
    env_file: ./tunedown/.env
    volumes:
      - ./tunedown:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  backend:
    build:
      context: ./backend-xrpl
      dockerfile: dev.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend-xrpl:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+asyncpg://hindex8:azerty123@db/tunedown_db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: hindex8
      POSTGRES_PASSWORD: azerty123
      POSTGRES_DB: tunedown_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
