version: "3.4"

services:
  frontend:
    build:
      context: ./tunedown
      dockerfile: dev.Dockerfile
    environment:
      NODE_ENV: dev
    ports:
      - 3000:3000
    env_file: ./tunedown/.env
    volumes:
      - ./tunedown:/app
      - /app/node_modules
    command: npm run dev
  backend:
    build:
      context: ./backend-xrpl
      dockerfile: dev.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend-xrpl:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
