services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    environment:
      NODE_ENV: dev
    ports:
      - "3000:3000"
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+asyncpg://tunedown:azerty123@db:5432/tunedown_db
      - JWT_SECRET_KEY=a0d848b05c6acfea19953499f1a887fac36b2a28eba2a4fd1c26d7bbc3067682
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: tunedown
      POSTGRES_PASSWORD: azerty123
      POSTGRES_DB: tunedown_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
