version: "3.4"

services:
  front-end:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: dev
    ports:
      - 5173:5173
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev